## TF Syntex Basics

In [1]:
#!pip install tensorflow==1.3.0

In [2]:
import tensorflow as tf

C:\Users\Raka\anaconda3\envs\fb1\lib\site-packages\tensorflow\python\framework\dtypes.py:458: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Raka\anaconda3\envs\fb1\lib\site-packages\tensorflow\python\framework\dtypes.py:459: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Raka\anaconda3\envs\fb1\lib\site-packages\tensorflow\python\framework\dtypes.py:460: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Raka\anaconda3\envs\fb1\lib\site-packages\tensorflow\python\framework\dty

In [3]:
print(tf.__version__)

1.3.0


In [4]:
hello=tf.constant("Hello ")

In [5]:
world=tf.constant("World")

In [6]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [7]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [8]:
with tf.Session() as sess:
    result=sess.run(hello+world)

In [9]:
print(result)

b'Hello World'


In [10]:
a=tf.constant(10)

In [11]:
a

<tf.Tensor 'Const_2:0' shape=() dtype=int32>

In [12]:
b=tf.constant(20)

In [13]:
type(a)

tensorflow.python.framework.ops.Tensor

In [14]:
a+b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [15]:
a+b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [16]:

with tf.Session() as sess:
    result=sess.run(a+b)

In [17]:
result

30

In [18]:
const=tf.constant(10)

In [19]:
fill_mat=tf.fill((4,4),10)

In [20]:
myzeros=tf.zeros((4,4))

In [21]:
myones=tf.ones((4,4))

In [22]:
myrandn=tf.random_normal((4,4),mean=0,stddev=1.0)

In [23]:
myrandu=tf.random_uniform((4,4),minval=0,maxval=1)

In [24]:
my_ops=[const,fill_mat,myzeros,myrandn,myrandu]

In [25]:
sess=tf.InteractiveSession()

In [26]:
for op in my_ops:
    print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[-0.16035783  0.53485    -0.5568317   0.90606266]
 [-0.84740096  0.09713438  0.87602717  0.90916246]
 [-1.0930514   1.482799   -0.34453416 -0.97069484]
 [-0.3859888   0.5500725   0.9899474  -0.28172794]]


[[0.10577977 0.74821866 0.89614785 0.28057158]
 [0.96136355 0.20348966 0.5110035  0.8518381 ]
 [0.8191813  0.9331516  0.14457834 0.14722049]
 [0.74854195 0.65475786 0.8476976  0.9257697 ]]




In [27]:
a=tf.constant([ [1,2],
             [3,4] ])

In [28]:
a

<tf.Tensor 'Const_5:0' shape=(2, 2) dtype=int32>

In [29]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [30]:
b=tf.constant([[10] , [100]])

In [31]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [32]:
result=tf.matmul(a,b)

In [33]:
sess.run(result)

array([[210],
       [430]])

In [34]:
result.eval()

array([[210],
       [430]])

## TensorFlow Graph

In [35]:
import tensorflow as tf

In [36]:
n1=tf.constant(1)

In [37]:
n2=tf.constant(2)

In [38]:
n3=n1+n2

In [39]:
with tf.Session() as sess:
    result = sess.run(n3)

In [40]:
print(result)

3


In [41]:
print(n3)

Tensor("add_4:0", shape=(), dtype=int32)


In [42]:
print(tf.get_default_graph())

In [43]:
g=tf.Graph()

In [44]:
print(g)

In [45]:
graph_one=tf.get_default_graph()

In [46]:
print(graph_one)

In [47]:
graph_two=tf.Graph()

In [48]:
print(graph_two)

In [49]:
with graph_two.as_default():
    print(graph_two is tf.get_default_graph())

True


In [50]:
print(graph_two is tf.get_default_graph())

False


## Variable and PlaceHolders

In [51]:
sess=tf.InteractiveSession()

In [52]:
my_tensor = tf.random_uniform((4,4),0,1)

In [53]:
my_tensor

<tf.Tensor 'random_uniform_1:0' shape=(4, 4) dtype=float32>

In [54]:
my_var = tf.Variable(initial_value=my_tensor)

In [55]:
print(my_var)

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32_ref>


In [56]:
#sess.run(my_var)

In [57]:
init = tf.global_variables_initializer()

In [58]:
sess.run(init)

In [59]:
sess.run(init)

In [60]:
sess.run(my_var)

array([[0.5717424 , 0.96436095, 0.67547846, 0.6429285 ],
       [0.8106983 , 0.93019533, 0.00547385, 0.25106108],
       [0.5315225 , 0.3717178 , 0.29895973, 0.49204993],
       [0.9363816 , 0.6065161 , 0.48898995, 0.38833833]], dtype=float32)

In [61]:
#PlaceHolders
ph=tf.placeholder(tf.float32,shape=(None,5))

## First TF Neural Network

In [62]:
import numpy as np
import tensorflow as tf

In [63]:
np.random.seed(101)
tf.set_random_seed(101)

In [64]:
rand_a = np.random.uniform(0,100,(5,5))
rand_a

array([[51.63986277, 57.06675869,  2.84742265, 17.15216562, 68.52769817],
       [83.38968626, 30.69662197, 89.36130797, 72.15438618, 18.99389542],
       [55.42275911, 35.2131954 , 18.18924027, 78.56017619, 96.54832224],
       [23.23536618,  8.35614337, 60.35484223, 72.89927573, 27.62388285],
       [68.53063288, 51.78674742,  4.84845374, 13.78692376, 18.69674261]])

In [65]:
rand_b=np.random.uniform(0,100,(5,1))

In [66]:
rand_b

array([[99.43179012],
       [52.06653967],
       [57.87895355],
       [73.48190583],
       [54.19617722]])

In [67]:
a=tf.placeholder(tf.float32)

In [68]:
b=tf.placeholder(tf.float32)

In [69]:
tf.multiply(a,b)

<tf.Tensor 'Mul:0' shape=<unknown> dtype=float32>

In [70]:
add_op=a+b

In [71]:
mul_op=a*b

In [72]:
with tf.Session() as sess:
    add_result=sess.run(add_op,feed_dict={a:rand_a,b:rand_b})
    print(add_result)
    print("\n")
    mult_result=sess.run(mul_op,feed_dict={a:rand_a,b:rand_b})
    print(mult_result)

[[151.07166  156.49855  102.27921  116.58396  167.95949 ]
 [135.45622   82.76316  141.42784  124.22093   71.06043 ]
 [113.30171   93.09215   76.06819  136.43912  154.42728 ]
 [ 96.71727   81.83804  133.83675  146.38118  101.10579 ]
 [122.72681  105.982925  59.044632  67.9831    72.89292 ]]


[[5134.644   5674.25     283.12433 1705.4707  6813.8315 ]
 [4341.8125  1598.267   4652.734   3756.8293   988.94635]
 [3207.8113  2038.1029  1052.7742  4546.9805  5588.1157 ]
 [1707.379    614.02527 4434.989   5356.7773  2029.8555 ]
 [3714.0984  2806.6438   262.76764  747.19855 1013.292  ]]
